### ISSUE TITLE
Domain doesn't use system provided AWS provider.

### ISSUE THREAD

**Issue by drthornt** [ramrexx/CloudForms_Essentials#8]
I was poking around ec2_synchronize_tags and saw that it makes it's own EC2 client object (using the old "cfme system provided" ruby sdk 1.54).

This means that it doesn't use the system defined proxy config.

I've written a bit about this here:

http://talk.manageiq.org/t/help-getting-access-to-server-config-proxy-url/1724

My question to ManageIQ/Redhat is: how does my "user space" domain access "VMDB::Util.http_proxy_uri" which I think is private.

Now that I think of it an alternative is to use the systems provided AWS provder / client. I'm going to look into how one might do that .In my mind ideally this domain should be able to use the system provided provider but I'm pretty ignorant of the nuts and bolts and hows and whys.

Any comment / ideas?

David

**Comment by ramrexx** [comment]
David,
I have not been able to find a clean and reliable way to get this proxy information. It is not as simple as reading the config file because the advance settings yml file is configured on each appliance. Meaning that one appliance could potentially be configured differently from another and this would lead to inconsistencies. 

Closing this issue for now.
